import { defineConfig } from 'astro/config';

// Staging build for btf.net on Cloudflare Pages (project temp-btf).
// The Framer-derived pages and assets live in site/ (generated by scripts/build_site.py
// from the local-only source-framer/ export). `npm run build` first renders the committed
// approved-copy snapshot into .generated/site/ (scripts/copy/render.mjs, offline), and
// Astro serves that folder as its static files. src/pages/404.astro adds the real 404 page.
export default defineConfig({
  publicDir: '.generated/site',
  outDir: 'dist',
  devToolbar: { enabled: false },
});
